name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Apply patch
        run: cd hugo/hugo && git apply ../../patch/20221224-update-add-goldmark-math.patch
        

      - name: Generate build files
        uses: thatisuday/go-cross-build@master
        with:
            platforms: 'linux/amd64, darwin/amd64, windows/amd64'
            package: 'hugo'
            name: 'hugo/hugo'
            dest: 'dist'

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: dist/
